Implemented frienships
jdmartinez1062/ror-social-scaffold pull request #2
Opened 2020-06-05 00:10 UTC by jdmartinez1062

Implemented friendships functionality along with pending friend requests and friend requests pages.

2020-06-05 20:40 UTC, kobiyoyo requested changes
## Hi Team     ![](https://user-images.githubusercontent.com/38801423/62908122-703d4480-bd44-11e9-9115-42025ab7f341.png) 
#### Great Job so far, but there are a few more things required. 
### General
- [ ] I can see Posts from other users that are not my friends.
- [ ] No button to  reject a friendship request
- [ ] Anytime i accept one friend request, all other friends are added to my friends list.
- [ ] check comments below
### Make changes and submit another code review request.
*Happy coding* 
(Any questions Feel free to contact me on slack @kobiyoyo)

2020-06-05 20:40 UTC, kobiyoyo commented on app/models/user.rb
> +  has_many :friendships, foreign_key: :user_id, class_name: 'Friendship'
this should be written like this `has_many :friendships`

2020-06-05 20:40 UTC, kobiyoyo commented on app/controllers/users_controller.rb
> +    retunr unless (fstatus = current_user.status?(find_user))
this should be `return`

2020-06-06 22:31 UTC, Ispirett approved these changes
# Status Approved  :1st_place_medal: 
Great job @jdmartinez1062  with changes made, you did well. :1st_place_medal:

2020-06-08 18:42 UTC, merged